### Get all employess
GET http://localhost:3000/api/employees

### Get employee by ID
GET http://localhost:3000/api/employees/6988091bec231bfa6af0faa9

### Create a new employee
POST http://localhost:3000/api/employees
Content-Type: application/json

 {
    "employeeId": 688,
    "name": "Rafael",
    "lastName": "Miranda",
    "email": "rafael.miranda@comeri.org.uy",
    "mobileNumber": 9798798,
    "position": "Data Analyst",
    "department": "IT"
  } 

### Update an existing employee
PUT http://localhost:3000/api/employees/6988091bec231bfa6af0faa9
Content-Type: application/json

  {
    "employeeId": 10938,
    "name": "Santiago",
    "lastName": "Risso",
    "email": "santiago.risso@comeri.org.uy",
    "mobileNumber": 92198888,
    "position": "Senior Developer",
    "department": "IT"
  }

### Delete an employee
DELETE http://localhost:3000/api/employees/698817bca6b20444f182676b